FROM rocker/tidyverse:4.4.2

LABEL maintainer="Daniel Miller <dmiller15@chop.edu>"
LABEL description="tidyverse image with gridExtras for generating GATK HardFilteirng charts"

RUN install2.r gridExtra

COPY Dockerfile .
