FROM ubuntu:18.04
MAINTAINER Miguel Brown (brownm28@email.chop.edu)

ENV SEURAT_VERSION=2.6

RUN apt update && apt install -y wget software-properties-common add-apt-repository ppa:webupd8team/java; \
