version: 2.1
orbs:
  docker: circleci/docker@2.0.3
commands:
  run_if_modified:
    description: Run steps if files are modified
    parameters:
      always-run-on-branch:
        default: ''
        description: The branch to always run the steps on
        type: string
      base-branch:
        default: master
        description: The branch against which to check against. This can also be a
          commit SHA
        type: string
      check-last-commit-on-base-branch:
        default: false
        description: This will make the check run for the latest commit on the base
          branch.
        type: boolean
      pattern:
        default: .*
        description: |
          The regex to match files against. The command uses grep to search file names.
          If you want to enforce starting with use ^. For checking if files in src/ or lib/ were modified,
          the pattern to use would be ^src.*|^lib.*
        type: string
      steps-to-run:
        default: []
        description: The steps to run if the files mentioned are modified
        type: steps
      use-divergence-point:
        default: false
        description: Find the divergence from the branch passed above, rather than
          the current HEAD
        type: boolean
    steps:
    - run:
        command: |
          if [ -z "$BASH" ]; then
            echo Bash not installed.
            exit 1
          fi
          git status >/dev/null 2>&1 || { echo >&2 "Not in a git directory or no git"; exit 1; }
          circleci-agent >/dev/null 2>&1 || { echo >&2 "No Circle CI agent. These are in all Circle CI containers"; exit 1; }

          if [ "$CIRCLE_BRANCH" == "<< parameters.always-run-on-branch >>" ]; then
            echo "Should always run on << parameters.always-run-on-branch >>. Exiting and continuing to run"
            exit 0;
          fi

          FILES_MODIFIED=""
          setcommit () {
            FILES_MODIFIED=$(git diff --name-only origin/<< parameters.base-branch >>..HEAD | grep -i -E '<< parameters.pattern >>')
            <<# parameters.use-divergence-point >>
            FILES_MODIFIED=$(git diff --name-only $(git merge-base HEAD origin/<< parameters.base-branch >>)..HEAD | grep -i -E '<< parameters.pattern >>')
            <</ parameters.use-divergence-point >>
            <<# parameters.check-last-commit-on-base-branch >>
            if [[ "$CIRCLE_BRANCH" == "<< parameters.base-branch >>" ]]; then
              FILES_MODIFIED=$(git diff --name-only HEAD~1 HEAD | grep -i -E '<< parameters.pattern >>')
            fi
            <</ parameters.check-last-commit-on-base-branch >>
          }

          setcommit || true
          if [ -z "$FILES_MODIFIED" ]
          then
            echo "Files not modified. Halting job"
            circleci-agent step halt
          else
            echo "Files modified, continuing steps"
          fi
        name: Only run if modified
    - steps: << parameters.steps-to-run >>
workflows:
  monthly:
    triggers:
    - schedule:
        cron: 57 0 1 * *
        filters:
          branches:
            only:
            - master
    jobs:
    - docker/publish:
        name: bixtools_gistic_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: gistic
        path: bixtools/gistic/
        docker-context: bixtools/gistic/
    - docker/publish:
        name: bixtools_bwa-samtools_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bwa-samtools
        path: bixtools/bwa-samtools/
        docker-context: bixtools/bwa-samtools/
    - docker/publish:
        name: bixtools_WGSA_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: WGSA
        path: bixtools/WGSA/
        docker-context: bixtools/WGSA/
    - docker/publish:
        name: bixtools_seqkit:2.3.1_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: seqkit:2.3.1
        path: bixtools/seqkit:2.3.1/
        docker-context: bixtools/seqkit:2.3.1/
    - docker/publish:
        name: bixtools_mend_qc_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: mend_qc
        path: bixtools/mend_qc/
        docker-context: bixtools/mend_qc/
    - docker/publish:
        name: bixtools_snpEff_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: snpEff
        path: bixtools/snpEff/
        docker-context: bixtools/snpEff/
    - docker/publish:
        name: bixtools_vcf_utils_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: vcf_utils
        path: bixtools/vcf_utils/
        docker-context: bixtools/vcf_utils/
    - docker/publish:
        name: bixtools_PureCN_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: PureCN
        path: bixtools/PureCN/
        docker-context: bixtools/PureCN/
    - docker/publish:
        name: bixtools_stranded:1.0_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: stranded:1.0
        path: bixtools/stranded:1.0/
        docker-context: bixtools/stranded:1.0/
    - docker/publish:
        name: bixtools_bvcftools_monthly
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bvcftools
        path: bixtools/bvcftools/
        docker-context: bixtools/bvcftools/
  diff:
    jobs:
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_gistic_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: gistic
        path: bixtools/gistic/
        docker-context: bixtools/gistic/
        before_build:
        - run_if_modified:
            pattern: bixtools/gistic/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_bwa-samtools_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bwa-samtools
        path: bixtools/bwa-samtools/
        docker-context: bixtools/bwa-samtools/
        before_build:
        - run_if_modified:
            pattern: bixtools/bwa-samtools/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_WGSA_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: WGSA
        path: bixtools/WGSA/
        docker-context: bixtools/WGSA/
        before_build:
        - run_if_modified:
            pattern: bixtools/WGSA/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_seqkit:2.3.1_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: seqkit:2.3.1
        path: bixtools/seqkit:2.3.1/
        docker-context: bixtools/seqkit:2.3.1/
        before_build:
        - run_if_modified:
            pattern: bixtools/seqkit:2.3.1/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_mend_qc_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: mend_qc
        path: bixtools/mend_qc/
        docker-context: bixtools/mend_qc/
        before_build:
        - run_if_modified:
            pattern: bixtools/mend_qc/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_snpEff_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: snpEff
        path: bixtools/snpEff/
        docker-context: bixtools/snpEff/
        before_build:
        - run_if_modified:
            pattern: bixtools/snpEff/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_vcf_utils_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: vcf_utils
        path: bixtools/vcf_utils/
        docker-context: bixtools/vcf_utils/
        before_build:
        - run_if_modified:
            pattern: bixtools/vcf_utils/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_PureCN_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: PureCN
        path: bixtools/PureCN/
        docker-context: bixtools/PureCN/
        before_build:
        - run_if_modified:
            pattern: bixtools/PureCN/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_stranded:1.0_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: stranded:1.0
        path: bixtools/stranded:1.0/
        docker-context: bixtools/stranded:1.0/
        before_build:
        - run_if_modified:
            pattern: bixtools/stranded:1.0/Dockerfile
    - docker/publish:
        filters:
          branches:
            ignore:
            - master
        context: dockerhub-vars
        name: bixtools_bvcftools_diff
        deploy: false
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bvcftools
        path: bixtools/bvcftools/
        docker-context: bixtools/bvcftools/
        before_build:
        - run_if_modified:
            pattern: bixtools/bvcftools/Dockerfile
  merge:
    jobs:
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_gistic_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: gistic
        path: bixtools/gistic/
        docker-context: bixtools/gistic/
        before_build:
        - run_if_modified:
            pattern: bixtools/gistic/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_bwa-samtools_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bwa-samtools
        path: bixtools/bwa-samtools/
        docker-context: bixtools/bwa-samtools/
        before_build:
        - run_if_modified:
            pattern: bixtools/bwa-samtools/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_WGSA_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: WGSA
        path: bixtools/WGSA/
        docker-context: bixtools/WGSA/
        before_build:
        - run_if_modified:
            pattern: bixtools/WGSA/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_seqkit:2.3.1_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: seqkit:2.3.1
        path: bixtools/seqkit:2.3.1/
        docker-context: bixtools/seqkit:2.3.1/
        before_build:
        - run_if_modified:
            pattern: bixtools/seqkit:2.3.1/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_mend_qc_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: mend_qc
        path: bixtools/mend_qc/
        docker-context: bixtools/mend_qc/
        before_build:
        - run_if_modified:
            pattern: bixtools/mend_qc/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_snpEff_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: snpEff
        path: bixtools/snpEff/
        docker-context: bixtools/snpEff/
        before_build:
        - run_if_modified:
            pattern: bixtools/snpEff/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_vcf_utils_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: vcf_utils
        path: bixtools/vcf_utils/
        docker-context: bixtools/vcf_utils/
        before_build:
        - run_if_modified:
            pattern: bixtools/vcf_utils/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_PureCN_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: PureCN
        path: bixtools/PureCN/
        docker-context: bixtools/PureCN/
        before_build:
        - run_if_modified:
            pattern: bixtools/PureCN/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_stranded:1.0_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: stranded:1.0
        path: bixtools/stranded:1.0/
        docker-context: bixtools/stranded:1.0/
        before_build:
        - run_if_modified:
            pattern: bixtools/stranded:1.0/Dockerfile
            check-last-commit-on-base-branch: true
    - docker/publish:
        filters:
          branches:
            only:
            - master
        name: bixtools_bvcftools_merge
        context: dockerhub-vars
        deploy: true
        registry: pgc-images.sbgenomics.com
        image: d3b-bixu/bixtools
        tag: bvcftools
        path: bixtools/bvcftools/
        docker-context: bixtools/bvcftools/
        before_build:
        - run_if_modified:
            pattern: bixtools/bvcftools/Dockerfile
            check-last-commit-on-base-branch: true
