version: 2.1
orbs:
  docker: circleci/docker@1.3.0
workflows:
  monthly:
    triggers:
    - schedule:
        cron: '* * 1 * *'
        filters:
          branches:
            only:
            - master
    jobs:
    - docker/publish:
        deploy: false
        image: kfdrc/verifybamid
        tag: latest
        path: verifybamid/latest/
        docker-context: verifybamid/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/verifybamid
        tag: 1.0.1
        path: verifybamid/1.0.1/
        docker-context: verifybamid/1.0.1/
    - docker/publish:
        deploy: false
        image: kfdrc/verifybamid
        tag: 1.0.2
        path: verifybamid/1.0.2/
        docker-context: verifybamid/1.0.2/
    - docker/publish:
        deploy: false
        image: kfdrc/arriba
        tag: latest
        path: arriba/latest/
        docker-context: arriba/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/arriba
        tag: 1.0.1
        path: arriba/1.0.1/
        docker-context: arriba/1.0.1/
    - docker/publish:
        deploy: false
        image: kfdrc/arriba
        tag: 1.1.0
        path: arriba/1.1.0/
        docker-context: arriba/1.1.0/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: 2.14.0
        path: picard/2.14.0/
        docker-context: picard/2.14.0/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: latest
        path: picard/latest/
        docker-context: picard/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: 2.8.3
        path: picard/2.8.3/
        docker-context: picard/2.8.3/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: 2.18.9
        path: picard/2.18.9/
        docker-context: picard/2.18.9/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: 2.17.4
        path: picard/2.17.4/
        docker-context: picard/2.17.4/
    - docker/publish:
        deploy: false
        image: kfdrc/picard
        tag: 2.15.0
        path: picard/2.15.0/
        docker-context: picard/2.15.0/
    - docker/publish:
        deploy: false
        image: kfdrc/lumpy-sv
        tag: 0.3.0
        path: lumpy-sv/0.3.0/
        docker-context: lumpy-sv/0.3.0/
    - docker/publish:
        deploy: false
        image: kfdrc/lumpy-sv
        tag: 0.2.13
        path: lumpy-sv/0.2.13/
        docker-context: lumpy-sv/0.2.13/
    - docker/publish:
        deploy: false
        image: kfdrc/SVTyper
        tag: 0.7.1
        path: SVTyper/0.7.1/
        docker-context: SVTyper/0.7.1/
    - docker/publish:
        deploy: false
        image: kfdrc/cutadapt
        tag: latest
        path: cutadapt/latest/
        docker-context: cutadapt/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/VarDictJava
        tag: fp_filter
        path: VarDictJava/fp_filter/
        docker-context: VarDictJava/fp_filter/
    - docker/publish:
        deploy: false
        image: kfdrc/VarDictJava
        tag: 1.5.8
        path: VarDictJava/1.5.8/
        docker-context: VarDictJava/1.5.8/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa-picard
        tag: latest
        path: bwa-picard/latest/
        docker-context: bwa-picard/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa-picard
        tag: broad
        path: bwa-picard/broad/
        docker-context: bwa-picard/broad/
    - docker/publish:
        deploy: false
        image: kfdrc/python
        tag: 2.7.13
        path: python/2.7.13/
        docker-context: python/2.7.13/
    - docker/publish:
        deploy: false
        image: kfdrc/smoove
        tag: 0.2.5
        path: smoove/0.2.5/
        docker-context: smoove/0.2.5/
    - docker/publish:
        deploy: false
        image: kfdrc/cellranger
        tag: '3.1'
        path: cellranger/3.1/
        docker-context: cellranger/3.1/
    - docker/publish:
        deploy: false
        image: kfdrc/bcbio
        tag: variation_recall-0.2.4
        path: bcbio/variation_recall-0.2.4/
        docker-context: bcbio/variation_recall-0.2.4/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa-bundle
        tag: 0.1.17
        path: bwa-bundle/0.1.17/
        docker-context: bwa-bundle/0.1.17/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk-picard
        tag: 4.beta.1-2.8.3
        path: gatk-picard/4.beta.1-2.8.3/
        docker-context: gatk-picard/4.beta.1-2.8.3/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk-picard
        tag: 4.0.1.2-2.8.3
        path: gatk-picard/4.0.1.2-2.8.3/
        docker-context: gatk-picard/4.0.1.2-2.8.3/
    - docker/publish:
        deploy: false
        image: kfdrc/manta
        tag: '1.6'
        path: manta/1.6/
        docker-context: manta/1.6/
    - docker/publish:
        deploy: false
        image: kfdrc/manta
        tag: '1.4'
        path: manta/1.4/
        docker-context: manta/1.4/
    - docker/publish:
        deploy: false
        image: kfdrc/velocyto
        tag: 0.17.17
        path: velocyto/0.17.17/
        docker-context: velocyto/0.17.17/
    - docker/publish:
        deploy: false
        image: kfdrc/speedseq
        tag: latest
        path: speedseq/latest/
        docker-context: speedseq/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/svaba
        tag: 1.1.0
        path: svaba/1.1.0/
        docker-context: svaba/1.1.0/
    - docker/publish:
        deploy: false
        image: kfdrc/lancet
        tag: 1.0.7
        path: lancet/1.0.7/
        docker-context: lancet/1.0.7/
    - docker/publish:
        deploy: false
        image: kfdrc/sambamba
        tag: 0.7.1
        path: sambamba/0.7.1/
        docker-context: sambamba/0.7.1/
    - docker/publish:
        deploy: false
        image: kfdrc/sambamba
        tag: 0.6.3
        path: sambamba/0.6.3/
        docker-context: sambamba/0.6.3/
    - docker/publish:
        deploy: false
        image: kfdrc/picard-r
        tag: picard2.8.3-r3.3.3
        path: picard-r/picard2.8.3-r3.3.3/
        docker-context: picard-r/picard2.8.3-r3.3.3/
    - docker/publish:
        deploy: false
        image: kfdrc/picard-r
        tag: picard2.15.0-r.3.3.3
        path: picard-r/picard2.15.0-r.3.3.3/
        docker-context: picard-r/picard2.15.0-r.3.3.3/
    - docker/publish:
        deploy: false
        image: kfdrc/VEP
        tag: r98
        path: VEP/r98/
        docker-context: VEP/r98/
    - docker/publish:
        deploy: false
        image: kfdrc/VEP
        tag: r93_v2
        path: VEP/r93_v2/
        docker-context: VEP/r93_v2/
    - docker/publish:
        deploy: false
        image: kfdrc/VEP
        tag: r94
        path: VEP/r94/
        docker-context: VEP/r94/
    - docker/publish:
        deploy: false
        image: kfdrc/VEP
        tag: r93
        path: VEP/r93/
        docker-context: VEP/r93/
    - docker/publish:
        deploy: false
        image: kfdrc/canvas
        tag: 1.11.0
        path: canvas/1.11.0/
        docker-context: canvas/1.11.0/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa
        tag: 0.7.15-r1140
        path: bwa/0.7.15-r1140/
        docker-context: bwa/0.7.15-r1140/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa
        tag: latest
        path: bwa/latest/
        docker-context: bwa/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/bwa
        tag: 0.7.17-r1188
        path: bwa/0.7.17-r1188/
        docker-context: bwa/0.7.17-r1188/
    - docker/publish:
        deploy: false
        image: kfdrc/star
        tag: 2.7.5a
        path: star/2.7.5a/
        docker-context: star/2.7.5a/
    - docker/publish:
        deploy: false
        image: kfdrc/star
        tag: 2.6.1d
        path: star/2.6.1d/
        docker-context: star/2.6.1d/
    - docker/publish:
        deploy: false
        image: kfdrc/star
        tag: fusion-1.5.0
        path: star/fusion-1.5.0/
        docker-context: star/fusion-1.5.0/
    - docker/publish:
        deploy: false
        image: kfdrc/codex2
        tag: '3.8'
        path: codex2/3.8/
        docker-context: codex2/3.8/
    - docker/publish:
        deploy: false
        image: kfdrc/sv2
        tag: latest
        path: sv2/latest/
        docker-context: sv2/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/FusionCatcher
        tag: latest
        path: FusionCatcher/latest/
        docker-context: FusionCatcher/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/controlfreec
        tag: '11.5'
        path: controlfreec/11.5/
        docker-context: controlfreec/11.5/
    - docker/publish:
        deploy: false
        image: kfdrc/LinkedSV
        tag: latest
        path: LinkedSV/latest/
        docker-context: LinkedSV/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.6
        path: gatk/4.beta.6/
        docker-context: gatk/4.beta.6/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.0.1.0
        path: gatk/4.0.1.0/
        docker-context: gatk/4.0.1.0/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.1
        path: gatk/4.beta.1/
        docker-context: gatk/4.beta.1/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.1.1.0
        path: gatk/4.1.1.0/
        docker-context: gatk/4.1.1.0/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.1-3.5
        path: gatk/4.beta.1-3.5/
        docker-context: gatk/4.beta.1-3.5/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.1.7.0R
        path: gatk/4.1.7.0R/
        docker-context: gatk/4.1.7.0R/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.5-tabix
        path: gatk/4.beta.5-tabix/
        docker-context: gatk/4.beta.5-tabix/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.0.12.0
        path: gatk/4.0.12.0/
        docker-context: gatk/4.0.12.0/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: latest
        path: gatk/latest/
        docker-context: gatk/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 3.8_ubuntu
        path: gatk/3.8_ubuntu/
        docker-context: gatk/3.8_ubuntu/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.6-tabix
        path: gatk/4.beta.6-tabix/
        docker-context: gatk/4.beta.6-tabix/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.0.5.2
        path: gatk/4.0.5.2/
        docker-context: gatk/4.0.5.2/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 3.5-0-g36282e4
        path: gatk/3.5-0-g36282e4/
        docker-context: gatk/3.5-0-g36282e4/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.beta.5
        path: gatk/4.beta.5/
        docker-context: gatk/4.beta.5/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 3.6-0-g89b7209
        path: gatk/3.6-0-g89b7209/
        docker-context: gatk/3.6-0-g89b7209/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: 4.0.1.2
        path: gatk/4.0.1.2/
        docker-context: gatk/4.0.1.2/
    - docker/publish:
        deploy: false
        image: kfdrc/gatk
        tag: '3.8'
        path: gatk/3.8/
        docker-context: gatk/3.8/
    - docker/publish:
        deploy: false
        image: kfdrc/bed_tools
        tag: bedopsv2.4.36_plus_bedtools
        path: bed_tools/bedopsv2.4.36_plus_bedtools/
        docker-context: bed_tools/bedopsv2.4.36_plus_bedtools/
    - docker/publish:
        deploy: false
        image: kfdrc/peddy
        tag: latest
        path: peddy/latest/
        docker-context: peddy/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/samtools
        tag: 1.7-11-g041220d
        path: samtools/1.7-11-g041220d/
        docker-context: samtools/1.7-11-g041220d/
    - docker/publish:
        deploy: false
        image: kfdrc/samtools
        tag: '1.9'
        path: samtools/1.9/
        docker-context: samtools/1.9/
    - docker/publish:
        deploy: false
        image: kfdrc/samtools
        tag: '1.6'
        path: samtools/1.6/
        docker-context: samtools/1.6/
    - docker/publish:
        deploy: false
        image: kfdrc/samtools
        tag: 1.3.1
        path: samtools/1.3.1/
        docker-context: samtools/1.3.1/
    - docker/publish:
        deploy: false
        image: kfdrc/samtools
        tag: latest
        path: samtools/latest/
        docker-context: samtools/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/annovar
        tag: latest
        path: annovar/latest/
        docker-context: annovar/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/seurat
        tag: latest
        path: seurat/latest/
        docker-context: seurat/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/annoFuse
        tag: 0.1.8
        path: annoFuse/0.1.8/
        docker-context: annoFuse/0.1.8/
    - docker/publish:
        deploy: false
        image: kfdrc/pizzly
        tag: latest
        path: pizzly/latest/
        docker-context: pizzly/latest/
    - docker/publish:
        deploy: false
        image: kfdrc/BIC-seq2
        tag: 0.7.2
        path: BIC-seq2/0.7.2/
        docker-context: BIC-seq2/0.7.2/
